[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.pdo",
  "php82Extensions.pdo_mysql",
  "php82Extensions.mbstring",
  "php82Extensions.openssl",
  "php82Extensions.tokenizer",
  "php82Extensions.xml",
  "php82Extensions.curl"
]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "php artisan key:generate --force",
  "php artisan config:clear",
  "php artisan config:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"